spring:
  datasource:
    url: jdbc:mysql://xxx:3306/zfc_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 2000
    jedis:
      pool:
        max-idle: 8
        max-wait:
        min-idle: 0
        max-active: 8
mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
server:
  port: 9008
